### PR TITLE
Adding cors

### LINKED ISSUE #21: Add cors to express server
When making requests to the rbac server from the market, browsers require cors to be enabled.

### PR DESCRIPTION
**Pull request by jamiehewitt15**
Closes #21 

Changes proposed in this PR:
- Enabling cors on the express server

### CODE REVIEW

**Review by alexcos20 — COMMENTED** [review]
can we keep npm 6, at least for a while?

all other components are using npm 6, so if you have to work on both rbac & ocean.js, you will have issues

**Comment by jamiehewitt15** [comment]
@alexcos20 My understanding was that we upgraded ocean.js to npm 7 here: https://github.com/oceanprotocol/ocean.js/pull/704

**Comment by alexcos20** [comment]
it's still v1:

https://github.com/oceanprotocol/ocean.js/blob/main/package-lock.json#L4

**Comment by jamiehewitt15** [comment]
Ah ok, I see. Ocean.js was bumped up to lockfileVersion 2 here: https://github.com/oceanprotocol/ocean.js/blob/7b6621d69e58708819c5cd0cce92451ac8489d1a/package-lock.json#L4 but it has since been downgraded again (possibly by mistake).

I've downgraded to lockfileVersion 1 on this PR now.  I'll move the npm upgrade out of this PR into a separate one so that it can be done at the same time as ocean.js

**Review by dungeonhao — APPROVED** [review]

**Pull request merged**
